name: build Task

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  config_and_build:
    name: Config libraries and build
    runs-on: ubuntu-latest
    outputs:
      # release-version: ${{ steps.validate-tag.outputs.release-version }}
      llvm-version: ${{ steps.get-versions.outputs.llvm-version }}
      mingw-version: ${{ steps.get-versions.outputs.mingw-version }}
      openssl-version: ${{ steps.get-versions.outputs.openssl-version }}
      qt-version: ${{ steps.get-versions.outputs.qt-version }}
      build-data: ${{ steps.date.outputs.date }}
    steps:
      - name: generate library version files
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: generate version files
        run: |
          python3 ./utils/version.py
          ls -l versions
          
      - name: get versions
        id: get-versions
        run: |
          echo "llvm-version=$(cat versions/llvm)" >> $GITHUB_OUTPUT
          echo "mingw-version=$(cat versions/mingw)" >> $GITHUB_OUTPUT
          echo "openssl-version=$(cat versions/openssl)" >> $GITHUB_OUTPUT
          echo "qt-version=$(cat versions/qt)" >> $GITHUB_OUTPUT

      - name: get build date      
        id: date        
        run: |  
           echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  check-versions:
    name: Check versions
    runs-on: ubuntu-latest
    needs: get-versions
    steps:
      - name: show library versions
        run: |
          echo "llvm-version=${{ needs.get-versions.outputs.llvm-version }}"
          echo "mingw-version=${{ needs.get-versions.outputs.mingw-version }}"
          echo "openssl-version=${{ needs.get-versions.outputs.openssl-version }}"
          echo "qt-version=${{ needs.get-versions.outputs.qt-version }}"

  build-deps:
    name: Build Dependencies
    needs:
      - get-versions
      - check-versions
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - windows-2022
           

    uses: ./.github/workflows/build_openssl.yml
    with:
      openssl-version: ${{ needs.get-versions.outputs.openssl-version }}
      mingw: ${{ needs.get-versions.outputs.mingw-version }}
      qt-version: ${{ needs.get-versions.outputs.qt-version }}
      build-date: ${{ needs.date.outputs.date }}
      upload: true
      runs-on: ${{ matrix.runs-on }}
      
    
    
    # Called workflows don't have access to secrets by default, so we need to explicitly pass secrets that we use.
    # secrets:
    #   RELEASE_TASKS_USER_TOKEN: ${{ secrets.RELEASE_TASKS_USER_TOKEN }}
